# Generated by Django 3.2 on 2024-05-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_devices_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='name',
            field=models.CharField(default='default name', max_length=100),
        ),
    ]
