# Generated by Django 3.2 on 2024-06-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20240526_2226'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.AddField(
            model_name='settings',
            name='parameter3',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='settings',
            name='parameter4',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='settings',
            name='sensor_name',
            field=models.CharField(default='default name', max_length=100),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='deviceconfig',
            name='volmax',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='deviceconfig',
            name='volmin',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='outlier',
            name='data',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='sensor1',
            name='value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='sensor2',
            name='value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='sensor3',
            name='value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='sensor4',
            name='value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='sensor5',
            name='value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='sensor6',
            name='value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='sensor7',
            name='value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='sensor8',
            name='value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='settings',
            name='parameter1',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='settings',
            name='parameter2',
            field=models.FloatField(default=0.0),
        ),
    ]
