# Generated by Django 3.2 on 2024-06-07 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20240608_0115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='parameter1',
            new_name='param1',
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='parameter2',
            new_name='param2',
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='parameter3',
            new_name='param3',
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='parameter4',
            new_name='param4',
        ),
    ]
