# Generated by Django 3.2 on 2024-06-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20240608_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='sensor_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
