# Generated by Django 3.2 on 2024-06-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_settings_sensor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='sensor_name',
            field=models.CharField(default='default_sensor', max_length=100),
        ),
    ]
