# Generated by Django 3.2 on 2024-06-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_settings_sensor_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='param1',
            new_name='max_alarm',
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='param2',
            new_name='max_value',
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='param3',
            new_name='min_alarm',
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='param4',
            new_name='min_value',
        ),
        migrations.AddField(
            model_name='settings',
            name='unit',
            field=models.CharField(default='default unit', max_length=50),
        ),
        migrations.AlterField(
            model_name='settings',
            name='sensor_name',
            field=models.CharField(default='default name', max_length=255),
        ),
    ]
