# Generated by Django 3.2 on 2024-06-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20240608_1222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensor3',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sensor5',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sensor7',
            options={},
        ),
        migrations.AlterField(
            model_name='sensor1',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sensor2',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sensor3',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sensor4',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sensor5',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sensor6',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sensor7',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sensor8',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
