# Generated by Django 3.2 on 2024-06-19 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_sensor9'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=50)),
                ('gpio', models.IntegerField()),
                ('min_alarm', models.FloatField()),
                ('max_alarm', models.FloatField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RS485Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('baudrate', models.IntegerField()),
                ('port', models.CharField(max_length=50)),
                ('sensor_id', models.IntegerField()),
                ('address', models.IntegerField()),
                ('sensor_type', models.CharField(max_length=50)),
                ('min_alarm', models.FloatField()),
                ('max_alarm', models.FloatField()),
            ],
        ),
    ]
