# Generated by Django 3.2 on 2024-06-20 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_digitalsettings_rs485settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.CharField(max_length=10)),
                ('param1', models.FloatField()),
                ('param2', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Outlier',
        ),
    ]
